name: ${pluginName}
version: ${version}
author: [ProgrammerDan]
description: ${description}
api-version: ${api_version}
softdepend: [RecipeManager, Citadel, NameLayer, HiddenOre, CropControl, ExilePearl, CrazyCrates]
main: com.programmerdan.minecraft.civspy.CivSpy
commands:
permissions:
